"""Creative model for ad content"""
from sqlalchemy import String, Integer, ForeignKey, Enum, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.ext.mutable import MutableDict
from typing import Optional
import enum

from .base import Base, TimestampMixin


class CreativeFormat(str, enum.Enum):
    """Creative format enum"""
    IMAGE = "image"
    VIDEO = "video"
    CAROUSEL = "carousel"
    COLLECTION = "collection"


class CreativeStatus(str, enum.Enum):
    """Creative status enum"""
    DRAFT = "draft"
    REVIEW = "review"
    APPROVED = "approved"
    REJECTED = "rejected"
    ACTIVE = "active"
    ARCHIVED = "archived"


class Creative(Base, TimestampMixin):
    """
    Ad creative - copy, images, videos.
    
    Generated by AI with brand compliance checks.
    """
    __tablename__ = "creatives"

    id: Mapped[int] = mapped_column(primary_key=True)
    persona_id: Mapped[Optional[int]] = mapped_column(ForeignKey("personas.id"))
    
    # Identity
    name: Mapped[str] = mapped_column(String(200))
    format: Mapped[CreativeFormat] = mapped_column(
        Enum(CreativeFormat, native_enum=False, validate_strings=True)
    )
    status: Mapped[CreativeStatus] = mapped_column(
        Enum(CreativeStatus, native_enum=False, validate_strings=True),
        default=CreativeStatus.DRAFT
    )
    
    # Copy content
    headline: Mapped[Optional[str]] = mapped_column(String(255))
    primary_text: Mapped[Optional[str]] = mapped_column(Text)
    description: Mapped[Optional[str]] = mapped_column(String(500))
    call_to_action: Mapped[Optional[str]] = mapped_column(String(50))
    
    # Media
    media: Mapped[dict] = mapped_column(
        MutableDict.as_mutable(JSONB), default=dict)
    # Example:
    # {
    #   "images": [
    #     {"url": "https://...", "hash": "abc123", "width": 1200, "height": 628}
    #   ],
    #   "videos": [
    #     {"url": "https://...", "thumbnail": "https://...", "duration": 15}
    #   ]
    # }
    
    # Compliance & quality
    risk_flags: Mapped[dict] = mapped_column(
        MutableDict.as_mutable(JSONB), default=dict)
    # Example:
    # {
    #   "compliance_issues": [],
    #   "toxicity_score": 0.02,
    #   "brand_alignment": 0.95,
    #   "readability_grade": 8
    # }
    
    # Generation metadata
    generation_prompt: Mapped[Optional[str]] = mapped_column(Text)
    model_version: Mapped[Optional[str]] = mapped_column(String(50))
    generation_params: Mapped[dict] = mapped_column(
        MutableDict.as_mutable(JSONB), default=dict)
    
    # Performance tracking
    variants: Mapped[dict] = mapped_column(
        MutableDict.as_mutable(JSONB), default=dict)
    # Track A/B test variants
    
    # Relationships
    persona: Mapped[Optional["Persona"]] = relationship(back_populates="creatives")
    ads: Mapped[list["Ad"]] = relationship(back_populates="creative")
