UPDATE units SET image_url = CASE slug
  WHEN 'marina-vista-tower' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/marina-vista-tower.jpg'
  WHEN 'marina-heights' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/marina-heights.jpg'
  WHEN 'marina-edge' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/marina-edge.jpg'
  WHEN 'downtown-residences' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/downtown-residences.jpg'
  WHEN 'burj-vista' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/burj-vista.jpg'
  WHEN 'downtown-avenue' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/downtown-avenue.jpg'
  WHEN 'creek-harbour-vista' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/creek-harbour-vista.jpg'
  WHEN 'creek-residences' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/creek-residences.jpg'
  WHEN 'creek-waterfront' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/creek-waterfront.jpg'
  WHEN 'palm-jumeirah-suites' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/palm-jumeirah-suites.jpg'
  WHEN 'palm-signature-villas' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/palm-signature-villas.jpg'
  WHEN 'palm-beach-residences' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/palm-beach-residences.jpg'
  WHEN 'business-bay-tower' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/business-bay-tower.jpg'
  WHEN 'bay-central' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/bay-central.jpg'
  WHEN 'bay-premium' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/bay-premium.jpg'
  WHEN 'jvc-apartments' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/jvc-apartments.jpg'
  WHEN 'jvc-heights' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/jvc-heights.jpg'
  WHEN 'jvc-townhouses' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/jvc-townhouses.jpg'
  WHEN 'hills-estate' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/hills-estate.jpg'
  WHEN 'hills-park' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/hills-park.jpg'
  WHEN 'hills-boulevard' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/hills-boulevard.jpg'
  WHEN 'mbr-lagoon' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/mbr-lagoon.jpg'
  WHEN 'mbr-hartland' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/mbr-hartland.jpg'
  WHEN 'mbr-villas' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/mbr-villas.jpg'
  WHEN 'ranches-villas' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/ranches-villas.jpg'
  WHEN 'ranches-townhouses' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/ranches-townhouses.jpg'
  WHEN 'south-apartments' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/south-apartments.jpg'
  WHEN 'expo-residences' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/expo-residences.jpg'
  WHEN 'south-villas' THEN 'https://mnckoafqhbotdpqzrlsj.supabase.co/storage/v1/object/public/media/inventory/south-villas.jpg'
  ELSE image_url END
WHERE slug IN ('marina-vista-tower', 'marina-heights', 'marina-edge', 'downtown-residences', 'burj-vista', 'downtown-avenue', 'creek-harbour-vista', 'creek-residences', 'creek-waterfront', 'palm-jumeirah-suites', 'palm-signature-villas', 'palm-beach-residences', 'business-bay-tower', 'bay-central', 'bay-premium', 'jvc-apartments', 'jvc-heights', 'jvc-townhouses', 'hills-estate', 'hills-park', 'hills-boulevard', 'mbr-lagoon', 'mbr-hartland', 'mbr-villas', 'ranches-villas', 'ranches-townhouses', 'south-apartments', 'expo-residences', 'south-villas');
